esphome:
  name: data-harvester
  on_boot:
    priority: 600
    then:
      delay: 3s


esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
  logs:
    bh1750.sensor: NONE
    sht3xd: NONE
    sensor: NONE
    i2c.arduino: NONE
    logger: NONE
    scd4x: NONE

i2c:
  sda: 18
  scl: 19
  scan: true
  id: bus_a

sensor:  
  - platform: scd4x
    address: 0x62
    id: scd4x_sensor
    co2:
      name: "scd4x_co2"
      id: scd4x_co2
      on_value:
        then:
          logger.log:
            format: "co2_sensor: %.4f"
            args: [ 'id(scd4x_co2).state']
    measurement_mode: single_shot
    update_interval: 5s

  - platform: bh1750
    name: "bh1750_lux"
    id: bh1750_lux
    address: 0x23
    update_interval: 5s
    on_value:
      then:
        logger.log:
          format: "light_sensor: %.4f"
          args: [ 'id(bh1750_lux).state' ]

    
  - platform: sht3xd
    temperature:
      name: "sht3xd_temp"
      id: sht3xd_temp
      on_value:
        then:
          logger.log:
            format: "temp_sensor: %.4f"
            args: [ 'id(sht3xd_temp).state']
    humidity:
      name: "sht3xd_humi"
      id: sht3xd_hum
      on_value:
        then:
          logger.log:
            format: "humi_sensor: %.4f"
            args: [ 'id(sht3xd_hum).state']
    update_interval: 5s